I have added Binary search algorithm to the code base and I want add other different algorithms and data structures too in various programming languages.
OpenCSAlgorithms/algorithms-data-structures pull request #4
Opened 2024-02-08 13:52 UTC by Udbhav-regadamilli

2024-02-08 15:38 UTC, TommasoFerrario18 commented
Hi @Udbhav-regadamilli, we are happy to receive your pull request and we are happy to combine your work with ours.  We will accept your pull request as soon as we have set up the entire development environment. Also we are still define how to organize the code.

Our idea is to separate the implementation from the signature of the methods, so that we can create a common interface for each operation, for example: create a list of "abstract" classes and the various implementations in other classes.

Also we are intrested in which programming languages you want to implement other things.

Now we are working on a GitHub action that compiles, executes tests, creates a package and the end update the doc.

2024-02-08 15:55 UTC, Tezze2001 requested changes

2024-02-08 15:55 UTC, Tezze2001 commented on src/Algorithms/binary_search.cpp
> +using namespace std;
remove using directive and adjust the source code to make compilable

2024-02-08 15:55 UTC, Tezze2001 commented on src/Algorithms/binary_search.cpp
> +int binarySearch(const vector<int>& arr, int target) {
use templates in place of int type

2024-02-08 15:55 UTC, Tezze2001 commented on src/Algorithms/binary_search.cpp
> +
create a new namespace called sorting and put binarySearch function inside

2024-02-08 15:55 UTC, Tezze2001 commented on src/Algorithms/binary_search.cpp
- [ ] rename Algorithms folder in sorting
- [ ] rename binary_search.cpp in sorting.cpp, at the end you should have " ./src/sorting/sorting.cpp "
- [ ] create a file header called ./src/sorting/sorting.h and put inside the sing of binarySearch function (Attection: when you create header file you should managed double referencing using #ifndef macro)
- [ ] define a new namespace inside  ./src/sorting/sorting.h  and  ./src/sorting/sorting.cpp called sorting (name of the folder) and put the code inside

2024-02-08 15:55 UTC, Tezze2001 commented on src/Algorithms/binary_search.cpp
> +int main() {
move the main function inside ./tests folder

2024-02-08 16:03 UTC, Tezze2001 commented
If you want continue to contribute, we can talk together on Discord, in this way we can easily explain our goals!

Thank you for your work 🥇 !

2024-02-08 17:16 UTC, Udbhav-regadamilli commented
Hi @Tezze2001 ,

I think I have made all the specified changes with the code base.

- [x]  rename Algorithms folder in sorting
- [x]  rename binary_search.cpp in sorting.cpp, at the end you should have " ./src/sorting/sorting.cpp "
- [x]  create a file header called ./src/sorting/sorting.h and put inside the sing of binarySearch function (Attection: when you create header file you should managed double referencing using #ifndef macro)
- [x] define a new namespace inside ./src/sorting/sorting.h and ./src/sorting/sorting.cpp called sorting (name of the folder) and put the code inside

And yes I want to continue contributing.

2024-02-09 12:05 UTC, Tezze2001 commented
I can see only test file but not the other changes

2024-02-09 16:00 UTC, Udbhav-regadamilli commented
Now I have committed the changes, please verify them.

2024-02-10 07:41 UTC, Tezze2001 approved these changes
Perfect, thank you!

You can implement everything written in a issue, note that @TommasoFerrario18 is implementing linear data structures.

2024-02-10 07:41 UTC, merged